n_gen = 100                 # Number of generations
mutation_rate = 0.01        # Mutation rate
pob_size = 1000             # Poblation size
n_offspring = pob_size      # Number of children 
n_runs = 1                  # Runs of the algorithm 
t_MCF_20 = 1                # t_MCF selected for 20ºC
t_meas_20 = 2e-3            # Aperture of data
T = [-20,0,20,40,60,80]     # Temperatures
n_ttos = 392                # Number of transistors
n_pairs = int(n_ttos/2)     # Number of pairs
n_meas_T = 100              # Number of MCF measurement per temperature
n_meas = n_meas_T*len(T)    # Number of MCF measurement for all temperatures
comp_offset = 0             # Comparator offset
t_MCF_adp = False           # t_MCF adaptation according to temperature
stopping_crit = True        # Stopping criteria
stop_limit = 10             # Stop limit
k_b = 8.617315e-5           # Boltzmann constant to adapt with temperature
Ea_adp = 0.7                # Mean activation energy to adapt with temperature
fitness = 'Rel_all'         # Fitness function (NSP or Rel_all)
P = 1                       # Probability value for the NSP fitness function